# Generated by Django 4.2 on 2023-04-10 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realtrips.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_start', models.PositiveIntegerField()),
                ('odometer_close', models.PositiveIntegerField()),
                ('journey_start', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Thika', 'Thika'), ('Malaa', 'Malaa'), ('Makongeni', 'Makongeni')], max_length=100)),
                ('journey_destination', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Thika', 'Thika'), ('Malaa', 'Malaa'), ('Makongeni', 'Makongeni')], max_length=100)),
                ('amount_collected', models.PositiveIntegerField()),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtrips.vehicle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realtrips.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FUEL-DIESEL', 'Fuel-Diesel'), ('BREAKFAST', 'Breakfast'), ('Lunch', 'Lunch'), ('Salaries', 'Salaries'), ('Parking Fee', 'Parking Fee'), ('Line', 'Line'), ('Boys', 'Boys'), ('Car Wash', 'Car Wash'), ('Oil/CC', 'Oil/CC'), ('Puncher', 'Puncher'), ('BREAKFAST', 'Breakfast'), ('Services', 'Services'), ('Greasing', 'Greasing'), ('Pad', 'Pad'), ('Garage', 'Garage'), ('Spare', 'Spare'), ('Tyre', 'Tyre'), ('Batteries', 'Batteries'), ('Break Fluid', 'Break Fluid'), ('Others', 'Others')], max_length=100)),
                ('amount_incurred', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtrips.vehicle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtrips.profile')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
