# Generated by Django 4.2 on 2023-04-10 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realtrips.vehicle')),
            ],
        ),
    ]
