# Generated by Django 4.2 on 2023-04-12 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0004_alter_expense_options_alter_expense_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='realtrips.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='realtrips.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='realtrips.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='realtrips.profile'),
        ),
    ]
