# Generated by Django 4.1.7 on 2023-04-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0005_driver_company_profile_company_vehicle_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='profilevehicle', to='realtrips.vehicle'),
            preserve_default=False,
        ),
    ]
