# Generated by Django 4.1.7 on 2023-04-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0006_remove_vehicle_user_profile_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='company',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='realtrips.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='realtrips.company'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='realtrips.company'),
        ),
    ]
