# Generated by Django 4.1.7 on 2023-04-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0007_remove_profile_vehicle_alter_company_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='profilevehicle', to='realtrips.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='realtrips.profile'),
        ),
    ]
