# Generated by Django 4.2 on 2023-04-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0014_alter_vehicle_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realtrips.vehicle'),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realtrips.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profilevehicle', to='realtrips.profile'),
        ),
    ]
