# Generated by Django 4.2 on 2023-04-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0015_alter_driver_vehicle_alter_route_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realtrips.profile'),
        ),
    ]
