# Generated by Django 4.2.2 on 2023-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0017_vehicle_fleet_no_alter_expense_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_conductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_inspector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
