# Generated by Django 4.2.2 on 2023-06-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtrips', '0018_alter_expense_options_alter_trip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.BooleanField(default='Pending'),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.BooleanField(default='Pending'),
        ),
    ]
