# Generated by Django 4.1.7 on 2023-04-02 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer_start', models.PositiveIntegerField()),
                ('odometer_close', models.PositiveIntegerField()),
                ('time', models.TimeField()),
                ('journey_start', models.CharField(choices=[('Nairobi-Thika', 'Nairobi-Thika'), ('Nairobi-Malaa', 'Nairobi-Malaa'), ('Nairobi-Makongeni', 'Nairobi-Makongeni')], max_length=100)),
                ('journey_destination', models.CharField(choices=[('Nairobi-Thika', 'Nairobi-Thika'), ('Nairobi-Malaa', 'Nairobi-Malaa'), ('Nairobi-Makongeni', 'Nairobi-Makongeni')], max_length=100)),
                ('amount_collected', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(choices=[('Nairobi-Thika', 'Nairobi-Thika'), ('Nairobi-Malaa', 'Nairobi-Malaa'), ('Nairobi-Makongeni', 'Nairobi-Makongeni')], default='Nairobi-Thika', max_length=100)),
                ('created', models.DateField()),
                ('Vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FUEL-DIESEL', 'Fuel-Diesel'), ('BREAKFAST', 'Breakfast'), ('Lunch', 'Lunch'), ('Salaries', 'Salaries'), ('Parking Fee', 'Parking Fee'), ('Line', 'Line'), ('Boys', 'Boys'), ('Car Wash', 'Car Wash'), ('Oil/CC', 'Oil/CC'), ('Puncher', 'Puncher'), ('BREAKFAST', 'Breakfast'), ('Services', 'Services'), ('Greasing', 'Greasing'), ('Pad', 'Pad'), ('Garage', 'Garage'), ('Spare', 'Spare'), ('Tyre', 'Tyre'), ('Batteries', 'Batteries'), ('Break Fluid', 'Break Fluid'), ('Others', 'Others')], max_length=100)),
                ('amount_incurred', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle')),
            ],
        ),
    ]
